# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TryRxAlamofire' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxCocoa'
  pod 'RxAlamofire'
  pod 'SwiftyJSON'

  # Pods for TryRxAlamofire

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
      config.build_settings['SWIFT_VERSION'] = '3.2'
    end
  end
end
