# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageFetcher' do
  use_frameworks!
  pod 'RxSwift', '~>4.0.0-beta.1'
  pod 'Alamofire'
  pod 'SwiftyJSON', '4.0.0-alpha.1'
end
